[tool.isort]
profile = "black"

[tool.mypy]
color_output = true
error_summary = true
ignore_missing_imports = true
pretty = true
strict_optional = true
warn_no_return = true
no_implicit_optional = true
warn_unused_configs = true
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_reexport = true
strict_equality = true
extra_checks = true
