codecov:
  require_ci_to_pass: true

coverage:
  status:
    project: false
    patch: false

bundle_analysis:
  warning_threshold: "5%"
  status: "informational"

comment:
  layout: "diff, files"
  behavior: default
  require_changes: true
  require_bundle_changes: true
