// note: we could import stancjs and get these at runtime,
// but that would result in bundling a duplicate copy of stancjs
// compared to the one we already have in the worker -- pretty heavy
const fs = require("fs");
try {
    fs.copyFileSync("src/app/Stanc/stanc.js", "./scripts/stanc.cjs");
    const stanc = require("./stanc.cjs");

    const mathSignatures = stanc.dump_stan_math_signatures().split("\n");
    const mathDistributions = stanc.dump_stan_math_distributions().split("\n");

    const json = {
        "_comment": "This file is generated by scripts/genStancConstants.cjs",
        mathSignatures,
        mathDistributions
    };

    fs.writeFileSync("src/app/Stanc/stancConstants.json", JSON.stringify(json));

} finally {
    fs.rmSync("./scripts/stanc.cjs");
}
